{{- if .Values.backend.enabled | default true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-backend" .Release.Name }}
  labels:
    app: {{ printf "%s-backend" .Release.Name }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.backend.service.type | default "ClusterIP" }}
  selector:
    app: {{ printf "%s-backend" .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port | default 8000 }}
      targetPort: {{ .Values.backend.service.port | default 8000 }}
{{- end }}
