replicaCount: 1

backend:
  enabled: true
  replicaCount: 1
  image:
    repository: city-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"
  probes:
    readiness:
      path: /health
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
    liveness:
      path: /health
      initialDelaySeconds: 15
      periodSeconds: 20
      failureThreshold: 3
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilization: 50
    targetMemoryUtilization: 80
    scaleUp:
      stabilizationWindowSeconds: 0
      policyPercent: 100
      periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policyPercent: 100
      periodSeconds: 60

frontend:
  enabled: true
  replicaCount: 1
  image:
    repository: city-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "150m"
      memory: "128Mi"

elasticsearch:
  enabled: true
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: "8.9.0"
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    type: ClusterIP
    port: 9200
  transportPort: 9300
  discoveryType: single-node
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

nodeSelector: {}
tolerations: []
affinity: {}
